---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      initContainers:
      - name: grafana-plugin-installer
        image: grafana/grafana:6.0.0
        command: ["grafana-cli", "--pluginsDir", "/data", "plugins", "install", "camptocamp-prometheus-alertmanager-datasource"]
        volumeMounts:
        - name: grafana-storage
          mountPath: /data
      containers:
      - name: grafana
        image: grafana/grafana:6.2.2
        env:
        - name: GF_PATHS_DATA
          value: /data
        - name: GF_PATHS_PLUGINS
          value: /data
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: password
        ports:
        - name: http
          containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
        volumeMounts:
        - name: grafana-storage
          mountPath: /data
        - name: grafana-dashboard-definitions-0
          mountPath: /grafana-dashboard-definitions/0
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
          readOnly: false
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
          readOnly: false
      volumes:
      - name: grafana-storage
        emptyDir: {}
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-dashboard-definitions-0
        configMap:
          name: grafana-dashboard-definitions-0
