apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - name: http
    nodePort: 30900
    port: 9090
    targetPort: 9090
  selector:
    prometheus: k8s
