---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-demo
  namespace: monitoring
  labels:
    monitoring: enabled
spec:
  selector:
    matchLabels:
      app: flask-demo
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 10s
